"""add conductor_id to telemetria_ruta

Revision ID: 1a939f717ea7
Revises: 536e415af9ed
Create Date: 2026-09-25 16:40:35.752932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a939f717ea7'
down_revision: Union[str, Sequence[str], None] = '536e415af9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetria_ruta', sa.Column('conductor_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_telemetria_ruta_conductor_id'), 'telemetria_ruta', ['conductor_id'], unique=False)
    op.create_foreign_key(
        'fk_telemetria_ruta_conductor_id_usuarios',
        'telemetria_ruta', 'usuarios',
        ['conductor_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_telemetria_ruta_conductor_id_usuarios', 'telemetria_ruta', type_='foreignkey')
    op.drop_index(op.f('ix_telemetria_ruta_conductor_id'), table_name='telemetria_ruta')
    op.drop_column('telemetria_ruta', 'conductor_id')
    # ### end Alembic commands ###
