"""add tabla usuarios y conductor_id a pedidos

Revision ID: 536e415af9ed
Revises: e50538433ee4
Create Date: 2026-09-25 16:10:44.007449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536e415af9ed'
down_revision: Union[str, Sequence[str], None] = 'e50538433ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('CONDUCTOR', 'DESPACHADOR', 'SUPERVISOR', 'ADMIN', name='rol_usuario_enum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index('ix_usuarios_email_activo', 'usuarios', ['email', 'activo'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_rol', 'usuarios', ['rol'], unique=False)
    op.add_column('pedidos', sa.Column('conductor_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_pedidos_conductor_id'), 'pedidos', ['conductor_id'], unique=False)
    op.create_foreign_key(
        'fk_pedidos_conductor_id_usuarios',
        'pedidos', 'usuarios',
        ['conductor_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pedidos_conductor_id_usuarios', 'pedidos', type_='foreignkey')
    op.drop_index(op.f('ix_pedidos_conductor_id'), table_name='pedidos')
    op.drop_column('pedidos', 'conductor_id')
    op.drop_index('ix_usuarios_rol', table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index('ix_usuarios_email_activo', table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
