"""add vehiculo_placa to pedidos

Revision ID: 6a9b4e645987
Revises: d5cfaa2cf201
Create Date: 2026-09-25 13:30:27.044512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9b4e645987'
down_revision: Union[str, Sequence[str], None] = 'd5cfaa2cf201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('vehiculo_placa', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'vehiculo_placa')
    # ### end Alembic commands ###
