"""creacion inicial tablas fuel

Revision ID: d5cfaa2cf201
Revises: 
Create Date: 2026-09-24 17:48:39.928873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5cfaa2cf201'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('qr_token', sa.String(length=256), nullable=False),
    sa.Column('qr_token_expira', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo_combustible', sa.Enum('GASOLINA_95', 'GASOLINA_91', 'DIESEL', name='tipo_combustible_enum'), nullable=False),
    sa.Column('volumen_cargado_l', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('volumen_recibido_l', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('temperatura_carga_c', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('temperatura_descarga_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('origen_nombre', sa.String(length=200), nullable=False),
    sa.Column('origen_lat', sa.Float(), nullable=False),
    sa.Column('origen_lon', sa.Float(), nullable=False),
    sa.Column('destino_nombre', sa.String(length=200), nullable=False),
    sa.Column('destino_lat', sa.Float(), nullable=False),
    sa.Column('destino_lon', sa.Float(), nullable=False),
    sa.Column('precintos', sa.JSON(), nullable=False),
    sa.Column('odometro_inicial_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('odometro_final_km', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('SOLICITADO', 'EN_TRANSITO', 'DESPACHANDO', 'COMPLETADO', 'ALERTA_MERMA', 'CANCELADO', name='estado_pedido_enum'), nullable=False),
    sa.Column('merma_teorica_l', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('merma_real_l', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('discrepancia_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('firma_despachador', sa.Text(), nullable=True),
    sa.Column('firma_conductor', sa.Text(), nullable=True),
    sa.Column('firma_receptor', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('volumen_cargado_l > 0', name='ck_pedido_vol_cargado_pos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_pedidos_codigo'), 'pedidos', ['codigo'], unique=True)
    op.create_index(op.f('ix_pedidos_estado'), 'pedidos', ['estado'], unique=False)
    op.create_index('ix_pedidos_estado_created', 'pedidos', ['estado', 'created_at'], unique=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('informes_entrega',
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('hse_checklist', sa.JSON(), nullable=False),
    sa.Column('hse_aprobado', sa.Boolean(), nullable=False),
    sa.Column('motivo_retraso', sa.Text(), nullable=True),
    sa.Column('retraso_minutos', sa.Integer(), nullable=True),
    sa.Column('merma_teorica_l', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('merma_real_l', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('discrepancia_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('alerta_merma_disparada', sa.Boolean(), nullable=False),
    sa.Column('token_validacion', sa.String(length=256), nullable=False),
    sa.Column('token_expira', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fotos_urls', sa.JSON(), nullable=False),
    sa.Column('video_evidencia_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id'),
    sa.UniqueConstraint('pedido_id', name='uq_informe_pedido'),
    sa.UniqueConstraint('token_validacion')
    )
    op.create_index(op.f('ix_informes_entrega_id'), 'informes_entrega', ['id'], unique=False)
    op.create_table('registro_paradas',
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracion_segundos', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Enum('DESCANSO_PROGRAMADO', 'TRAFICO', 'FALLA_MECANICA', 'CONTROL_POLICIAL', 'RECARGA_COMBUSTIBLE', 'EMERGENCIA_MEDICA', 'NO_AUTORIZADA', name='motivo_parada_enum'), nullable=False),
    sa.Column('dentro_geocerca', sa.Boolean(), nullable=False),
    sa.Column('geocerca_nombre', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_paradas_id'), 'registro_paradas', ['id'], unique=False)
    op.create_index(op.f('ix_registro_paradas_pedido_id'), 'registro_paradas', ['pedido_id'], unique=False)
    op.create_table('telemetria_ruta',
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('velocidad_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rumbo_grados', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precision_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('es_offline', sa.Boolean(), nullable=False),
    sa.Column('timestamp_gps', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_sync', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispositivo_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetria_pedido_gps_ts', 'telemetria_ruta', ['pedido_id', 'timestamp_gps'], unique=False)
    op.create_index(op.f('ix_telemetria_ruta_id'), 'telemetria_ruta', ['id'], unique=False)
    op.create_index(op.f('ix_telemetria_ruta_pedido_id'), 'telemetria_ruta', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetria_ruta_pedido_id'), table_name='telemetria_ruta')
    op.drop_index(op.f('ix_telemetria_ruta_id'), table_name='telemetria_ruta')
    op.drop_index('ix_telemetria_pedido_gps_ts', table_name='telemetria_ruta')
    op.drop_table('telemetria_ruta')
    op.drop_index(op.f('ix_registro_paradas_pedido_id'), table_name='registro_paradas')
    op.drop_index(op.f('ix_registro_paradas_id'), table_name='registro_paradas')
    op.drop_table('registro_paradas')
    op.drop_index(op.f('ix_informes_entrega_id'), table_name='informes_entrega')
    op.drop_table('informes_entrega')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_index('ix_pedidos_estado_created', table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_estado'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_codigo'), table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
