"""add observaciones_descarga to pedidos

Revision ID: e50538433ee4
Revises: 6a9b4e645987
Create Date: 2026-09-25 14:05:49.759278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50538433ee4'
down_revision: Union[str, Sequence[str], None] = '6a9b4e645987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('observaciones_descarga', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'observaciones_descarga')
    # ### end Alembic commands ###
